name: Test

on:
  pull_request:

jobs:
  TestWindows:
    runs-on: windows-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      
      - name: Set up Python 3.12.1
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.1
        
      - name: Install Dependencies
        run: | 
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Try building
        run: |
          pyinstaller --onefile app.py

      - name: List result
        run: |
          cd dist
          ls
        
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: TestWindows
          path: dist/app.exe
      - name: Give out pyinstaller version
        run: pyinstaller --version
  TestMac:
    runs-on: macos-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      
      - name: Set up Python 3.12.1
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.1
        
      - name: Install Dependencies
        run: | 
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Try building
        run: |
          pyinstaller --onefile app.py

      - name: Prepare
        run: |
          cd dist
          mv app macos-app
          chmod +x macos-app
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TestMac
          path: dist/macos-app

      - name: Give out pyinstaller version
        run: pyinstaller --version
